import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.rtl.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
// import "./style.css";
import "../styles/typographyStyles.css";
import "../styles/buttonsStyles.css";
import "../styles/bannerStyles.css";
import "../styles/formsStyles.css";
import "../styles/allSections.css";
import "../styles/faqStyles.css";
import "../styles/globalStyle.css";
import "../styles/preloaderStyles.css";
import "../styles/resetStyles.css";
import "../styles/responsiveStyles.css";
import "../styles/font.css";
import {yekanBakh} from "@/lib/fonts";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    keywords: ['Forex & Stock Broker Trading Signals', 'Review', 'Tutorial'],
    icons: {
        icon: '/assets/images/logo/favicons.png',
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
        <head>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </head>
        <body className={`${yekanBakh.variable}`}>
        {children}
        </body>
    </html>
  );
}
